# This is the default format. 
# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-katex

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
title : cgranade::space
tagline: 'Quantum, stats, programming, and some rants'
description:
    Research SDE at Microsoft Research
url: https://www.cgranade.com
baseurl: https://www.cgranade.com/

author :
  name : Christopher Granade
  email : cgranade@cgranade.com
  github : cgranade
  twitter : cgranade

github:
  repo: https://github.com/cgranade/cgranade.github.io

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["*.ipynb"]
