# This is the default format. 
# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-katex
  - jekyll-paginate

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
title : cgranade::space
tagline: 'Quantum, stats, programming, and some rants'
description: ""
url: https://www.cgranade.com
baseurl: /

author :
  name : Cassandra Granade
  email : cgranade@cgranade.com
  github : cgranade
  twitter : cgranade

github:
  repo: https://github.com/cgranade/cgranade.github.io

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["*.ipynb"]

katex:
  rendering_options:
    macros:
      "\\ket": "\\left|#1\\right\\rangle"

keep_files:
- .well-known
- .well-known/webfinger

include:
- .well-known
- .well-known/webfinger
